---
# This playbook deploys prestashop infra.  
- hosts: localhost
  #remote_user: root

  vars:
    - network: "10.0.1.0"
    - stackname: "psstack"
    - stackcmd: "../../heat/prestashop_v4.sh"
    - stackoutput: [ "server1_private_ip", "server2_private_ip", "asg_server_ips" ]

  roles:
    - v4/heatstack
    - { role: v4/hostkeys, when: newstack.changed or force_host_keys is defined }
