---
# This playbook deploys prestashop.  

- hosts: localhost
  #remote_user: root

  vars:
    - network: "10.0.1.0"
    - stackname: "prestashopstack"
    - stackcmd: "../../heat/prestashop_v1.sh"

  roles:
    - heatstack

  tasks:
    #- debug: msg="{{ newstack }}"

    - name: Manage host keys
      include: tasks/host_keys.yaml
      when: newstack.changed or force_host_keys is defined

- hosts: "{{ stackname }}-db"
  remote_user: centos
  become: yes
  #become_method: sudo

  vars:
    - stackname: "prestashopstack"
  
  roles:
    - db

- hosts: "{{ stackname }}-web"
  become: yes
  #become_method: sudo

  vars:
    - stackname: "prestashopstack"
  
  roles:
    - web
