---
# This playbook deploys prestashop.  

- hosts: localhost
  #remote_user: root

  vars:
    - network: "10.0.1.0"
    - stackname: "prestashopstack"
    - stackcmd: "../../heat/prestashop_v1.sh"

  roles:
    - heatstack

  tasks:
    - name: Manage host keys
      include: host_keys.yaml
      when: (newstack.skipped is not defined and not newstack.skipped) or force_host_keys is defined
