- name: Deploy devstack on baremetal
  hosts: all
  gather_facts: False
  remote_user: root

  vars:
    devstack_repo: git://github.com/openstack-dev/devstack.git
    #ctrl_ip: 192.168.27.100 should now come from deploy.sh
    version: stable/mitaka
    #floating_ip_range: 172.24.4.0/24 should now come from deploy.sh
    #labenv: True comes from deploy.sh
    #public_gw:172.24.x.1 comes from deploy.sh
    #floating_pool comes from deploy.sh
    heat: True
    neutron: True
    neutron_lbaasv2: False
    swift: True
    security_groups: True
    tempest: False
    app_catalog: False
    baremetal: True

  tasks:
    - name: create devstack user
      user: name=stack comment="Devstack user" shell=/bin/bash generate_ssh_key=yes ssh_key_bits=2048

    - name: allow sudo for devstack user
      lineinfile: "dest=/etc/sudoers regexp='^stack' line='stack ALL=(ALL) NOPASSWD: ALL'"

    - name: add root key to user stack
      shell: cat ~/.ssh/id_rsa.pub >> /home/stack/.ssh/authorized_keys

    - name: Correct ownership
      shell: chown stack:stack /home/stack/.ssh/authorized_keys

    - name: checkout devstack
      git: repo={{ devstack_repo }} dest=/home/stack/devstack version={{ version }} accept_hostkey=yes
      remote_user: stack

    - name: local.conf
      template: src=../common/templates/local.conf.j2 dest=/home/stack/devstack/local.conf
      remote_user: stack

    - name: source openrc in profile
      lineinfile: dest=/home/stack/.bashrc regexp=".*openrc" line='. /home/stack/devstack/openrc'
      remote_user: stack

    - name: Git user definition
      command: git config --global user.name "Uggla"
      remote_user: stack
      args:
        chdir: devstack

    - name: Git user definition
      command: git config --global user.email "uggla@free.fr"
      remote_user: stack
      args:
        chdir: devstack

    - name: Cherry pick path (https://review.openstack.org/#/c/336919/)
      shell: git fetch https://git.openstack.org/openstack-dev/devstack refs/changes/19/336919/1 && git cherry-pick FETCH_HEAD
      remote_user: stack
      args:
        chdir: devstack

    - name: Deploy devstack (Stack !!!)
      shell: ./stack.sh
      remote_user: stack
      args:
        chdir: devstack

    - name: Remove route to br-int
      shell: ip r del 10.0.0.0/24 via {{ vrgw }}

    - name: Get interface name
      shell: ip a | grep -B 2 10.3.222 | grep -P "^\d+:" | awk '{print $2}' | sed 's/://'
      register: interface

    - name: Allow devstack vm to access internet
      shell: iptables -t nat -A POSTROUTING -o {{ interface.stdout }} -j MASQUERADE
