---
- hosts: default
  vars:
    devstack_repo: git://github.com/openstack-dev/devstack.git
    #ctrl_ip: 192.168.27.100 should now come from Vagrantfile
    version: stable/mitaka
    #floating_ip_range: 172.24.4.0/24 should now come from Vagrantfile
    #labenv: True comes from Vagrantfile
    #public_gw:172.24.x.1 comes from Vagrantfile
    #floating_pool comes from Vagrantfile
    heat: True
    neutron: True
    neutron_lbaasv2: False
    swift: True
    security_groups: True
    tempest: False
    keyring_config_dir: /home/vagrant/.local/share/python_keyring
    app_catalog: False

  tasks:
    - name: devstack common part
      include: ../common/devstack.yml
