---
- hosts: default
  vars:
    devstack_repo: git://github.com/openstack-dev/devstack.git
    #ctrl_ip: 192.168.27.100 should now come from Vagrantfile
    version: stable/mitaka
    #floating_ip_range: 172.24.4.0/24 should now come from Vagrantfile
    #labenv: True comes from Vagrantfile
    #public_gw:172.24.x.1 comes from Vagrantfile
    #floating_pool comes from Vagrantfile
    heat: True
    neutron: True
    neutron_lbaasv2: False
    swift: True
    security_groups: True
    tempest: False
    keyring_config_dir: /home/vagrant/.local/share/python_keyring
    app_catalog: False

  tasks:
    - name: create keyring config directory
      file: >
        state=directory
        dest={{ keyring_config_dir }}

    - name: copy keyring config file to workaround https://bugs.launchpad.net/bugs/1242992
      copy: >
        src=files/keyringrc.cfg
        dest={{ keyring_config_dir }}/keyringrc.cfg

    - name: install git
      apt: "name=git update_cache=yes"
      sudo: True

    - name: checkout devstack
      git: repo={{ devstack_repo }} dest=/home/vagrant/devstack version={{ version }} accept_hostkey=yes

    - name: local.conf
      template: src=../common/templates/local.conf.j2 dest=/home/vagrant/devstack/local.conf

    - name: source openrc in profile
      lineinfile: dest=/home/vagrant/.profile regexp=".*openrc" line='. /home/vagrant/devstack/openrc'

    - name: enable eth2
      command: ip link set dev eth2 up
      sudo: True

    - name: Git user definition
      command: git config --global user.name "Uggla"
      args:
        chdir: devstack

    - name: Git user definition
      command: git config --global user.email "uggla@free.fr"
      args:
        chdir: devstack

    - name: Cherry pick path (https://review.openstack.org/#/c/336919/)
      shell: git fetch https://git.openstack.org/openstack-dev/devstack refs/changes/19/336919/1 && git cherry-pick FETCH_HEAD
      args:
        chdir: devstack

